WCS\CoavBundle\Entity\Flight:
    type: entity
    table: null
    repositoryClass: WCS\CoavBundle\Repository\FlightRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        arrival:
            type: string
            length: '4'
        pilot:
            type: string
            length: 255
            unique: true
        freeSeats:
            type: integer
            nullable: true
        takeoffTime:
            type: datetime
            unique: true
    lifecycleCallbacks: {  }

    manyToOne:
        departure:
            targetEntity: WCS\CoavBundle\Entity\Terrain
            InversedBy: departures